version: "3.8"

services:
  ollama:
    image: ollama/ollama:latest
    container_name: doc-query-service-ollama
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - web
      - default
    restart: unless-stopped

  #FastAPI backend
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: doc-query-service-backend
    env_file:
      - app/.env
    environment:
      - OLLAMA_HOST=http://doc-query-service-ollama:11434
    depends_on:
      - ollama
    restart: unless-stopped
    networks:
      - web
      - default
      - postgres-net

  #React Frontend + Nginx
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    container_name: doc-query-service-frontend
    networks:
      - web
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  ollama_data:

networks:
  web:
    external: true
    name: darsh05_web
  default:
    driver: bridge
  postgres-net:
    external: true
    name: doc-ai-agent_default
